#!/bin/sh

while :
do

clear

echo '### backup for proton packages'
echo 'bp - create .i386-wine-pkg.tar.xz'
echo 'bs - create .steam.tar.xz'
echo 'bu - create .archive.tar.xz (universal)'
echo '### linux libs for portwine or ubuntu service'
echo 'la - mkdir /usr/lib/x86_64-linux-gnu/ and download libs'
echo 'le - extract and move libs'
echo '### portwine'
echo 'pd - delete old installation of portwine'
echo 'pe - extra needed for installation'
echo 'pi - installation of portwine'
echo 'ps - start portwine'
echo '### service ubuntu compat'
echo 'sus - install service ubuntu with brave-browser'
echo '### system commands'
echo 'upd - close techno'
echo 'exit - close techno'
echo ''
echo -n 'Choose your number: '
 read ans
 case "$ans" in
  bp)
  cd /home/admin
  export XZ_OPT=-9 
  tar cvJf .i386-wine-pkg.tar.xz .i386-wine-pkg
  ;;
  bs)
  cd /home/admin
  export XZ_OPT=-9 
  tar cvJf .steam.tar.xz .steam
  ;;
  bu)
  cd /home/admin
  export XZ_OPT=-9 
  tar cvJf .archive.tar.xz .archive
  ;;
  la)
   sudo mkdir /usr/lib/x86_64-linux-gnu/
   lxterminal --geometry=40x4 -e 'chrome https://drive.google.com/file/d/1zq4wvy7Cu9h4tzPzXHrmulhQlpcPzjBz/view?usp=sharing' &
  ;;  
  le)
   cd cd /home/admin/Downloads
   unzip x86_64-linux-gnu.zip
   sudo mv x86_64-linux-gnu/* /usr/lib/x86_64-linux-gnu/
   cd ..
  ;; 
  pd)
   cd /home/admin
   rm -rf PortProton-95
   rm -rf .PortProton-95
  ;; 
  pe)
   fetch https://github.com/bsdver/to/archive/refs/heads/main.zip
   unzip main.zip
   sudo cp sha256sum /usr/local/bin/sha256sum
   sudo chmod +x /usr/local/bin/sha256sum
   sudo ln -s /usr/local/bin/bash /bin/bash
   rm -rf to-main
   rm main.zip
   sudo pkg ins pidof
  ;; 
  pi)
   lxterminal --geometry=80x20 -e 'wget -c -T 5 https://portwine-linux.ru/ftp/portwine/PortProton-95 && sh "./PortProton-95" &' 
  ;;
  ps)
   lxterminal --geometry=80x20 -e 'PortWINE/PortProton/data/scripts/start.sh %F ; /usr/local/bin/bash' & 
  ;; 
  sus)
   # depences  
   sudo pkg ins -y debootstrap
   
   # fetch files
   fetch https://github.com/bsdver/to/archive/refs/heads/main.zip
   unzip main.zip

   # autostart and some actions
   sudo mv to-main/script-techno-ubuntu /usr/local/etc/rc.d/ubuntu
   sudo chmod +x /usr/local/etc/rc.d/ubuntu
   sudo sysrc ubuntu_enable=YES
   sudo /usr/local/bin/bash -c 'mkdir -p {/compat/ubuntu/dev/fd,/compat/ubuntu/dev/shm,/compat/ubuntu/home,/compat/ubuntu/tmp,/compat/ubuntu/proc,/compat/ubuntu/sys}'
   sudo service ubuntu start
   sudo debootstrap --arch=amd64 --no-check-gpg focal /compat/ubuntu
   sudo service ubuntu restart
   cd /compat/ubuntu/lib64/ && sudo rm ./ld-linux-x86-64.so.2 ; sudo ln -s ../lib/x86_64-linux-gnu/ld-2.31.so ld-linux-x86-64.so.2
   cd ~

   # chroot
   sudo chroot /compat/ubuntu /bin/bash -c 'printf "%b\n" "0.0 0 0.0\n0\nUTC" > /etc/adjtime'
   sudo chroot /compat/ubuntu /bin/bash -c 'sudo dpkg-reconfigure tzdata'
   sudo chroot /compat/ubuntu /bin/bash -c 'printf "APT::Cache-Start 251658240;" > /etc/apt/apt.conf.d/00aptitude'
   sudo chroot /compat/ubuntu /bin/bash -c 'printf "deb http://archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse" > /etc/apt/sources.list'
   sudo chroot /compat/ubuntu /bin/bash -c 'apt update ; apt install -y apt-transport-https curl fonts-symbola gnupg pulseaudio'
   sudo chroot /compat/ubuntu /bin/bash -c 'curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -'
   sudo chroot /compat/ubuntu /bin/bash -c 'echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | tee /etc/apt/sources.list.d/brave-browser-release.list'
   sudo chroot /compat/ubuntu /bin/bash -c 'apt update ; apt install -y brave-browser'
   
   # copy other files
   sudo mv to-main/script-techno-brave-wrapper /compat/ubuntu/opt/brave.com/brave/brave-wrapper
   sudo chmod +x /compat/ubuntu/opt/brave.com/brave/brave-wrapper
   sudo mv to-main/script-techno-linux-brave /usr/local/bin/linux-brave
   sudo chmod +x /usr/local/bin/linux-brave
   sudo mv to-main/script-techno-brave-browser.desktop ~/.local/share/applications/brave-browser.desktop
   sudo chmod +x ~/.local/share/applications/brave-browser.desktop

   # clean
   rm -rf to-main
   rm main.zip
   
  ;;
  upd)
   ### update techno
   fetch https://github.com/bsdver/to/archive/refs/heads/main.zip
   unzip main.zip
   mv to-main/techno .techno
   sudo chmod +x .techno
   rm -rf to-main
   rm main.zip
   xterm -geometry 73x41-0-25 -e ./.techno &
   sleep 2
   break
  ;;
  exit)
   echo 'Exit.'
   sleep 1
   break
  ;;
  *)
   echo "Error. Please, type number. Start again..."
  ;;
 esac
done

